[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-Wl,-install_name,@rpath/libyanxu_sqlite_native.dylib"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=/ignore:4099"]
