[包]
格式 = 2
名称 = "言舟无文件权限消费者"
版本 = "0.1.0"
言序 = ">=1.1.12"
入口 = "主.yx"
说明 = "验证言舟文件数据库遵守应用权限"
许可 = "MIT"
作者 = ["言序社区"]

[依赖]
言舟 = { 路径 = "../..", 版 = "^0.1" }

[权限]
文件 = []
网络 = []
TCP监听 = []
UDP绑定 = []
环境 = []
进程 = false
原生扩展 = true

[导出]
默认 = "主.yx"

[构建]
目标 = "字节码"
